### ISSUE TITLE
VS Code snippets

### ISSUE THREAD

**Issue by mellson** [fhammerschmidt/awesome-rescript#1]
Hey @fhammerschmidt I've been meaning to share some of my Visual Studio Code ReScript snippets and keybindings. I could do it directly in this repo, which I personally think would be a great place. Or I can create a separate repo just for that. What's your preference?

My hope is that others will share their cool snippets and keybindings as we go

**Comment by fhammerschmidt** [comment]
You can add a separate md file to this repo if you like.
I added an [editor-support section](https://github.com/fhammerschmidt/awesome-rescript/blob/main/README.md#editor-support), maybe link to it there?

**Comment by mellson** [comment]
Great ideas, I'll do that.
